# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='desc',
            new_name='descripcion',
        ),
    ]
