# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20160912_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
